# RailSafe AI Monitoring System Configuration

# Model sozlamalari
model:
  path: "models/car_detect.v1.pt"
  target_classes: [0]  # 0: car, 2: truck, 3: bus, 5: train, 7: motorcycle
  class_names:
    
    0: "Car"

   


# Vaqt chegaralari (soniyalarda)
thresholds:
  warning: 10.0      # Ogohlantirish (sariq)
  violation: 15.0    # Qoida buzilishi (qizil)

# Ishlash parametrlari
processing:
  # 🚀 ADAPTIVE MODE - Avtomatik tezlik optimizatsiyasi
  adaptive_mode: true  # true = avtomatik, false = qo'lda
  frame_skip_idle: 3   # Hech narsa yo'q bo'lsa: har 2-frameda (RESURS TEJASH)
  frame_skip_active: 1 # Avtomobil detect qilsa: har frameda (REAL-TIME)
  
  # Eski usul (adaptive_mode: false bo'lsa ishlaydi)
  process_every_n_frames: 1  # Har bir frameni ishlash (1 = hammasi, 2 = har ikkinchi)
  
  polygon_length: 8.0        # Polygon uzunligi (metrda)

# Kameralar ro'yxati
cameras:
  - id: 1
    name: "Shimoliy Yo'nalish"
    source: "videos/192.168.170.160_02_20251013180043842.mp4"
    polygon_file: "paligons/labels_my-project-name_2025-10-15-10-00-23.json"
    enabled: true
  
  - id: 2
    name: "Janubiy Yo'nalish"
    source: "rtsp://admin:1q2w3e4r5t@192.168.170.160:554/Streaming/Channels/201"
    polygon_file: "polygons/paligon_pereezd.json"
    enabled: false
  
  - id: 3
    name: "Sharqiy Yo'nalish"
    source: "videos/192.168.170.160_02_20251013180043842.mp4"
    polygon_file: "/home/bahrombek/Desktop/RailSafeAI_v1.1/polygons/labels_my-project-name_2025-10-15-10-00-23.json"
    enabled: false
  
  - id: 4
    name: "G'arbiy Yo'nalish"
    source: "videos/192.168.170.160_02_20251013180043842.mp4"
    polygon_file: "/home/bahrombek/Desktop/RailSafeAI_v1.1/polygons/labels_my-project-name_2025-10-15-10-00-23.json"
    enabled: false

  - id: 5
    name: "G'arbiy Yo'nalish2"
    source: "videos/192.168.170.160_02_20251013180043842.mp4"
    polygon_file: "/home/bahrombek/Desktop/RailSafeAI_v1.1/polygons/labels_my-project-name_2025-10-15-10-00-23.json"
    enabled: false

  - id: 6
    name: "G'arbiy Yo'nalish1"
    source: "videos/192.168.170.160_02_20251013180043842.mp4"
    polygon_file: "/home/bahrombek/Desktop/RailSafeAI_v1.1/polygons/labels_my-project-name_2025-10-15-10-00-23.json"
    enabled: false
